// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtobusDeneyimleriAPI.Data;

#nullable disable

namespace OtobusDeneyimleriAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829125117_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("OtobusDeneyimleriAPI.Models.BusRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinationId = 1,
                            OriginId = 16,
                            Slug = "bursa-adana"
                        },
                        new
                        {
                            Id = 2,
                            DestinationId = 6,
                            OriginId = 34,
                            Slug = "istanbul-ankara"
                        });
                });

            modelBuilder.Entity("OtobusDeneyimleriAPI.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kamil Koç",
                            Slug = "kamil-koc"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pamukkale Turizm",
                            Slug = "pamukkale-turizm"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ali Osman Ulusoy",
                            Slug = "ali-osman-ulusoy"
                        });
                });

            modelBuilder.Entity("OtobusDeneyimleriAPI.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cleanliness")
                        .HasColumnType("REAL");

                    b.Property<double>("Comfort")
                        .HasColumnType("REAL");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OverallRating")
                        .HasColumnType("REAL");

                    b.Property<double>("Punctuality")
                        .HasColumnType("REAL");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Staff")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TravelDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RouteId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("OtobusDeneyimleriAPI.Models.Review", b =>
                {
                    b.HasOne("OtobusDeneyimleriAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtobusDeneyimleriAPI.Models.BusRoute", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Route");
                });
#pragma warning restore 612, 618
        }
    }
}
